FROM golang:1.8
RUN echo 'set -o vi' >> /root/.bashrc
RUN echo '\\pset null -null-\n\\pset pager off' >> /root/.psqlrc
RUN echo 'set editing-mode vi' >> /root/.inputrc

RUN apt-get update && apt-get install -y \
  less \
  postgresql \
  postgresql-contrib \
  screen \
  vim
RUN go get github.com/rnubel/pgmgr
RUN go get github.com/tools/godep

ENV USER root
ENV DSN postgres://postgres@db:5432/forty-thieves?sslmode=disable

ADD . /go/src/github.com/topher200/forty-thieves
WORKDIR /go/src/github.com/topher200/forty-thieves/webcmd
RUN go get -t
RUN godep go build

WORKDIR /go/src/github.com/topher200/forty-thieves
CMD ./test.sh
