{
 "title": "Forty Thieves",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Forty Thieves gameState processing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(forty_thieves_processed_states_total[10s])",
     "legendFormat": "game states processed, {{version}}"
    },
    {
     "expr": "rate(forty_thieves_new_saved_states_total[10s])",
     "legendFormat": "new saved game states, {{version}}"
    }
   ]
  },
  {
   "title": "Processed States",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "select game_id, score, move_num, status, game_state_id from game_state where status in ('PROCESSED') and game_id = (select id from game order by id desc limit 1) order by score asc, move_num asc limit 2;",
     "rawSql": "select game_id::integer, score::integer, move_num::integer, status, game_state_id \nfrom game_state \nwhere \n    status in ('PROCESSED') and \n    game_id = (select id from game order by id desc limit 1) \norder by score asc, move_num asc \nlimit 5"
    }
   ]
  },
  {
   "title": "Best Score",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT score \nFROM game_state \nWHERE game_id = (\n    SELECT id FROM game ORDER BY id DESC LIMIT 1\n)\nORDER BY score ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Number of 'Processed' States",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM game_state WHERE status = 'PROCESSED';"
    }
   ]
  },
  {
   "title": "Number of 'Claimed' States",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM game_state WHERE status = 'CLAIMED';"
    }
   ]
  },
  {
   "title": "Claimed States",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "select game_id, score, move_num, status, game_state_id from game_state where status in ('PROCESSED') and game_id = (select id from game order by id desc limit 1) order by score asc, move_num asc limit 2;",
     "rawSql": "select game_id::integer, score::integer, move_num::integer, status, game_state_id \nfrom game_state \nwhere \n    status in ('CLAIMED') and \n    game_id = (select id from game order by id desc limit 1) \norder by score asc, move_num asc \nlimit 5"
    }
   ]
  },
  {
   "title": "Number of 'Unprocessed' States",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM game_state WHERE status = 'UNPROCESSED';"
    }
   ]
  },
  {
   "title": "Unprocessed States",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "select game_id, score, move_num, status, game_state_id from game_state where status in ('PROCESSED') and game_id = (select id from game order by id desc limit 1) order by score asc, move_num asc limit 2;",
     "rawSql": "select game_id::integer, score::integer, move_num::integer, status, game_state_id \nfrom game_state \nwhere \n    status in ('UNPROCESSED') and \n    game_id = (select id from game order by id desc limit 1) \norder by score asc, move_num asc \nlimit 5"
    }
   ]
  }
 ]
}