#!/usr/bin/env bash

echo "Creating database forty-thieves..."
pgmgr db create

echo "Running migrations..."
pgmgr db migrate

echo "Creating database forty-thieves-test"
pgmgr -c ".pgmgr.test.json" db create

echo "Running migration on postgres://topher@localhost:5432/forty-thieves-test?sslmode=disable..."
pgmgr -c ".pgmgr.test.json" db migrate
