#!/usr/bin/env bash

echo "Creating database forty_thieves..."
pgmgr db create

echo "Running migrations..."
pgmgr db migrate

echo "Creating database forty_thieves_test"
pgmgr -c ".pgmgr.test.json" db create

echo "Running migration on postgres://topher@localhost:5432/forty_thieves_test?sslmode=disable..."
pgmgr -c ".pgmgr.test.json" db migrate
